dsite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('topico/', include('topico.urls')),
    path('', views.index, name='home'),
]

topico/urls.py
from django.urls import path
from . import views

app_name= 'topico'

urlpatterns =[
    path('', views.index, name='index'),
    path('add/', views.add,name='add')
]

topico/models.py
from django.db import models

# Create your models here.
class topicModel(models.Model):
    nome=models.CharField(max_length=30, null=False)
    password= models.CharField(null=False,blank=False)
    

dsite/views.py
from django.http import HttpResponse
from django.shortcuts import render

def index(respons):
    context={
        "nome":"vic"
    }
    return render(respons, 'dsite/index.html', context)

topico/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
import banco
def index(response):
    return render(response, "topico/index.html")
def add(request):
    condição = 0
    if request.method == "POST":
        try:
            banco.adicionar(str(request.POST.get('nome')),str(request.POST.get('password')))
            return redirect('topico:index')
        except:
            condição = 1
    context={
        "erro":condição
    }
    
    return render(request, 'topico/add.html', context)

templates/dsite/index.html
<!DOCTYPE html>

<html lang="pt-br">
<head>
		<meta http-equiv="CONTENT-TYPE" content="text/html; charset=UTF-8">
		<title>Hello, World!</title>
</head>
<body>
		<h1>
				Hello, World!{{nome}}!
				<a href="{% url 'topico:index' %}">entrar</a>
		</h1>
</body>
</html>

templates/topico/add.html
<!DOCTYPE html>

<html>
<head>
		<meta http-equiv="CONTENT-TYPE" content="text/html; charset=UTF-8">
		<title>Hello, World!</title>
</head>
<body>
		{% for a in range(5) %}
		<h1>
				add
		</h1>
		{% endfor %}
		<form action="" method="post">
				{% csrf_token %}
				<label for="nomei">nome:</label>
				<input name="nome" type="" id="nomei" maxlength="10" required="true">
				<br>
				<label for="nomei">senha:</label>
				<input name="password" type="password" id="nomei" minlength="8" maxlength="10" required="true">
				<br>
				<input type="submit" value="enviar">
				<p id="erro" style="color:red">Usuario já existente</p>
		</form>
		<script>
		var erro = {{erro}}
		dedect()
		
		function dedect(){
				
				var errod = document.getElementById('erro')
				if (erro == 0) {
						errod.style.display = "none"
				} else {
						errod.style.display = "display"
				}
				
		}
		</script>
</body>
</html>

templates/topico/index.html
<!DOCTYPE html>

<html>
<head>
		<meta http-equiv="CONTENT-TYPE" content="text/html; charset=UTF-8">
		<title>Hello, World!</title>
</head>
<body>
		<h1>
				topicos!
		</h1>
		<a href="{% url 'topico:add' %}">add</a>
</body>
</html>